
name: Tests

on:
  push:
    branches: [ "Test" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11.1
      uses: actions/setup-python@v3
      with:
        python-version: "3.11.1"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
  
    - name: Test with pytest
      run: |
        pytest
